koajs/jwt

- package.json
- test.js
Hello,
I am using your `koa-jwt` middleware for a project and noticed that `jsonwebtoken` has had a lot of version changes over the last 3 or 4 months. I have updated its version to the latest along with other dev dependencies which were out-of-date.
I ran through your suite of tests successfully and make a couple small updates there as well.
Please let me know if you have any questions.
Michael
> Update to the latest jsonwebtoken version

- index.js
- test.js
Using different secrets for different requests.
Users from App<n> request with HEADER {"X-Request-App": "App<n>", "Authorization": "Bearer <token>"} will use distributed secret<n>.
> To support dynamic secret provide by middleware

- package.json
> Set jsonwebtoken dependency to 5.x.x

- index.js
It's a server configuration error, so this should be reflected by the status code.
> Change "Invalid secret" status code to 500

- README.md
- index.js
- test.js
Makes finding a token a little more flexible.
> Get token refactor

- README.md
- lib/index.js
- package.json
- test/test.js
I have added the revoked feature. When the users want to check if the token is revoked, is possible with this new feature.
Thanks.
> add support to isRevoked check function

- package.json
- provide raw token on state by specifying
- use typeof instead of util.isFunction
- fix bug when Authorization header is two words but the first is not Bearer
> version 1.3.0

- lib/index.js
- test/test.js
Prevent default value for `opts.tokenKey` from overwriting `ctx.state.token`
> Prevent default value for `opts.tokenKey` from overwriting `ctx.state.token`

- README.md
Bit me this morning and didn't see anything in the readme so thought I should update it?
> Make note about no longer exporting sign

- .travis.yml
- README.md
- package.json
* Set the minimum engine to node 7.6
* bump the minor version
* remove the publishConfig so that npm publish defaults to latest tag
> Prepare to publish v2.x tagged as latest

- package.json
koa-unless v1.0.1 is broken, yet ( https://github.com/Foxandxss/koa-unless/issues/3#issuecomment-287544453 )
> Pin koa-unless dependency to version 1.0.0

- package.json
- types/index.d.ts
added TypeScript definitions from @types and also added some fixes that are still pending in DefinitelyTypes repo.
> added definitions for TypeScript

- README.md
> Fix JSDoc for isRevoked handler spec

- README.md
[https://github.com/koajs/jwt/blob/fb44b8596b24e7eda0a266a77dd69a02146d9ff0/lib/index.js#L39](https://github.com/koajs/jwt/blob/fb44b8596b24e7eda0a266a77dd69a02146d9ff0/lib/index.js#L39)
> fix typo in readme isRevoked argument order

- README.md
- lib/index.js
- package.json
- test/test.js
- yarn.lock
> Token expiration fixes #107

- lib/get-secret.js
- package.json
+ secret provider function -  add `decoded.payload` as argument
> + secret provider function -  add decoded.payload as argument

- lib/get-secret.js
- lib/index.js
- types/index.d.ts
related to https://github.com/koajs/jwt/issues/112
> Added isRevoked type definition

- package.json
- yarn.lock
For bug fixes and compatibility with newer node versions
> update jsonwebtoken to 8.5.1

- types/index.d.ts
It also matches the jsonwebtoken @types definition.
> Fix audience definition to match RFC

- types/index.d.ts
See Issue: https://github.com/koajs/jwt/issues/165
> Allow String arrays fro Options.issuer

- README.md
In example there is the missprint
> The missprint in code example

- README.md
https://github.com/dentarg/blog/blob/master/_posts/2014-01-07-angularjs-authentication-with-cookies-vs-token.markdown
> Update auth0 blog link to GitHub source

- README.md
This PR documents `debug` previously undocumented in the README.
> Detail explicitly middleware's options in README

- types/index.d.ts
> fix: Add useOriginalUrl to UnlessOptions type
