koajs/jwt

index.js

Basically exposes `JWT` package function as-is, without thunkification. Avoids surprises.

Expose the vanilla JWT function and not the thunkified ones

---

README.md
index.js
package.json
test.js

Hello @stiang and @citius.
As an alternative to #17 I created this PR using `koa-unless`.
This is what `express-jwt` does and I think it is more complete.
It allows you to conditionally run `koa-jwt`. You could skip it for certain URL, certain extensions or even provide a custom exception.
What do you think? :+1:

Add support for koa-unless

---

index.js
test.js

Using a HTTPS cookie in which to store the token may seem counter-intuitive, as sometimes the desire to use Auth headers is to move away from cookies. HTTPS cookies however, cannot be inspected from Javascript, whereas setting an Auth header from a front-end app must use some Javascript. So, storing the JWT in a HTTPS cookie can be safer as malicious Javascript is unable to steal the token so easily as if it is used somewhere in the code.
This pull request adds an option, under opts.cookie, which specifies the name of a cookie that can be the source of the JWT in addition to or instead of the Auth header.

add option to use token from a specific cookie

---

README.md
index.js
test.js

This adds a `opts.getToken` option.
This option takes precedence over other token retrieval options (headers, cookies, etc.). Users can pass a function that will be called with `this` being the Koa context and should return with the JWT to verify.
This would close #30

Add getToken functionality

---

README.md
index.js
package.json
test-server.js
test.js

- Upgrade koa in `devDependencies` to `^2.0.0`.
- Remove generators in favor of promise-based middleware.
- Update all unit tests.

Migrate to Koa v2 middleware syntax

---

lib/index.js

`util.isFunction` is deprecated since Node v4.0.0

use typeof instead of util.isFunction

---

index.js
test.js

This PR fixes the check in the `resolveAuthorizationHeader` function. Before this commit, koa-jwt would eventually respond with `No authentication token found` when there was a malformed auth token like `Beer sometoken` 🍻

Fix validation in resolveAuthorizationHeader

---

index.js
test.js

This extends the work done by @petermelias in https://github.com/koajs/jwt/pull/66.
When a token is successfully validated, the token is inserted into `this.state`. The key within `this.state` that the token is added to is set in `options.tokenKey` and defaults to `token`.

Populate state with undecoded token

---

lib/index.js
lib/verify.js
package.json

removes bluebird requirement and wraps the JWT verify function in a native promise.

remove bluebird

---

README.md
index.js

Before I update npm, I've changed the tokenKey functionality slightly. 
In case anyone is using the library already and have anything on `ctx.state.token`, to avoid accidentally clobbering ctx.state.token on an update of koa-jwt, `opts.tokenKey` does not have a default.
In order to have the token available on `ctx.state.token`, you need to specifically set `opts.tokenKey` to `token`.

update tokenKey for backward compatibility

---

lib/index.js
lib/resolvers/auth-header.js
lib/resolvers/cookie.js
lib/verify.js
package.json

* Bluebird has been removed in favour of a native promise wrapper around jsonwebtoken
* The complex and hard-to-follow promise chain has been reimplemented using `async / await`
* The resolver functions have been moved to their own files
* istanbul replaced with nyc for coverage

Remove Bluebird and refactor using async/await

---

.gitignore
lib/get-secret.js
lib/index.js
lib/resolvers/auth-header.js
lib/resolvers/cookie.js
package.json
test/test.js

* add `/.idea` to .gitignore for webstorm devs
* remove mocha `--bail` flag on test run to show all errors
* catch invalid token errors before calling secret provider function
* Remove the trailing newlines from thrown errors
* For security, when `debug`=`false`, all thrown errors have the same message
* Koa defaults `ctx.state` to `{}` so no need to do this ourselves
* add test for passthrough with bad token to give us 100% coverage
* fixed some minor linting issues and phrasing

Consistent error messages, 100% coverage, misc tweaks

---

types/index.d.ts

I added type definitions for commonly used options `audience`, `issuer`, and `algorithms`.
Related to #109

Added audience, issuer, and algorithms type definitions

---

lib/index.js

It's not necessary to use `ctx.throw()`

Make the code regular

---

package.json

+ [`jsonwebtoken`: v8.0.0 --> v8.3.0](https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md)
+ `koa-unless`: v1.0.0 --> v1.0.7 (no changelog)
This fixes the warning highlighted in #130:
```
warning koa-jwt > jsonwebtoken > lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray
```

Bumped jsonwebtoken from v8.0.0 to v8.3.0 (Fixes #130) 

---

README.md
types/index.d.ts

Also update readme with correct signature.
After I made this I found #122 and #123. The types here are better:
- #122 has deliberately vague type to work round rubbish types in another repo
- `object` used for the header param in #123 is the empty interface, which isn't what we want because it might have members
- the payload is actually only a string if it can't be decoded (see source for jsonwebtoken)

fix typescript definitions for koa

---

README.md
lib/index.js

When `passthrough` is true there is no way to catch errors.  I added original jwt errors in `ctx.state.jwtOriginalError`. This lets downstream middlewares handle JWT exceptions. I also updated readme file.

Lets downstream middlewares handle JWT exceptions 

---

types/index.d.ts

https://github.com/Foxandxss/koa-unless#current-options
> path it could be an string, a regexp or an array of any of those. If the request path match, the middleware will not run.
💖

koa-unless path supports strings, RegExps and arrays of these (typing issue).

---

.gitignore
.npmrc
.travis.yml
LICENSE
README.md
lib/index.js
package.json
test/test-server.js
test/test.js
yarn.lock

- update the `.gitignore` file.
- avoid `package-lock.json` file.
- update the `README.md` file.
- update all dependencies.
- fix the `LICENSE` file.
- update the pipeline `.travis.yml`.
- clean the test code by remove all unused vars .
- add all contributors to `package.json` file.
- fix the version in `package.json` file by sync with the release tag [here](https://github.com/koajs/jwt/releases).
> can go to next version 😊 ❤️ !

Update the repo 🚀 !

---

types/index.d.ts

fix types/index.ts, make the type hint support more argument for koa-unless, such as `custom, ext, method ...`
also the koa-unless path argument is optional,  not necessary.

updated typescript definitions, fix types/index.ts, make the type hint support more argument for koa-unless, such as `custom, ext, method

---

types/index.d.ts

`string[] | RegExp[]` only allows either array of `string` or array of `RegExp`.
`(string | RegExp)[]` allows array of `string` or `RegExp`.

Fix typing of `path` property

---

lib/resolvers/auth-header.js
package.json
test/test.js

HTTP spec permits optional leading / trailing whitespace in HTTP header values.
This adds support for Authorization headers that contain valid optional whitespace.
Issue: https://github.com/koajs/jwt/issues/156

Support whitespace pre bearer post colon

---

types/index.d.ts

According to the [readme](https://github.com/koajs/jwt#retrieving-the-token), `null` should be returned from `getToken` if the token is not found.

Fix typing of `getToken`

---

types/index.d.ts

Adds `Secret` and `UnlessOptions` interfaces, and reuses `Secret` in `SecretLoader`. Made these changes because I'd like to do something like this:
```ts
import jwt, { Options, UnlessOptions } from 'koa-jwt'
const jwtOptions: Options = {
secret: 'its',
key: 'a',
algorithms: ['me'],
cookie: 'mario',
passthrough: true,
}
const jwtAllowList: UnlessOptions = { path: ['/ping'] }
export const jwtMiddleware = jwt(jwtOptions).unless(jwtAllowList)
```

Export more interfaces
